ANALYZYING THIS HEALTHCARE DATASET

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Data importing

In [2]:
df = pd.read_csv("healthcare_dataset_.csv")
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,1/31/2024,Matthew Smith,Sons and Miller,Blue Cross,18856.28131,328,Urgent,2/2/2024,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,8/20/2019,Samantha Davies,Kim Inc,Medicare,33643.32729,265,Emergency,8/26/2019,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,9/22/2022,Tiffany Mitchell,Cook PLC,Aetna,27955.09608,205,Emergency,10/7/2022,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,11/18/2020,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.78241,450,Elective,12/18/2020,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,9/19/2022,Kathleen Hanna,White-White,Aetna,14238.31781,458,Urgent,10/9/2022,Penicillin,Abnormal

Data checking

In [6]:
df.shape

(55500, 15)

In [9]:

df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])

In [10]:
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])

In [11]:
df['billing_amount'] = pd.to_numeric(df['billing_amount'], errors='coerce')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                55500 non-null  object
 1   age                 55500 non-null  int64
 2   gender              55500 non-null  object
 3   blood_type          55500 non-null  object
 4   medical_condition   55500 non-null  object
 5   date_of_admission   55500 non-null  object
 6   doctor              55500 non-null  object
 7   hospital            55500 non-null  object
 8   insurance_provider  55500 non-null  object
 9   billing_amount      55500 non-null  float64
 10  room_number         55500 non-null  int64
 11  admission_type      55500 non-null  object
 12  discharge_date      55500 non-null  object
 13  medication          55500 non-null  object
 14  test_results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [13]:
df.describe()

                age  billing_amount   room_number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224655    202.000000
50%       52.000000    25538.069380    302.000000
75%       68.000000    37820.508432    401.000000
max       89.000000    52764.276740    500.000000

Data Cleaning

In [14]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [15]:
df.isnull().sum()

name                  0
age                   0
gender                0
blood_type            0
medical_condition     0
date_of_admission     0
doctor                0
hospital              0
insurance_provider    0
billing_amount        0
room_number           0
admission_type        0
discharge_date        0
medication            0
test_results          0
dtype: int64

Data formatting

In [16]:
df['name'] = df['name'].str.title()

In [20]:
df['date_of_admission'] = pd.to_datetime(df['date_of_admission'])

In [21]:
df['discharge_date'] = pd.to_datetime(df['discharge_date'])

In [22]:
df['length_of_stay'] = (df['discharge_date'] - df['date_of_admission']).dt.days

In [26]:
df.head()

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results,length_of_stay,age_group
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.28131,328,Urgent,2024-02-02,Paracetamol,Normal,2,Young Adult
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.32729,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6,Elderly
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.09608,205,Emergency,2022-10-07,Aspirin,Normal,15,Elderly
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.78241,450,Elective,2020-12-18,Ibuprofen,Abnormal,30,Young Adult
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.31781,458,Urgent,2022-10-09,Penicillin,Abnormal,20,Adult

Age check analysis

In [24]:
df['age_group'] = pd.cut(df['age'], 
                        bins=[0,18,35,60,100],
                        labels=['Child','Young Adult','Adult','Elderly'])

In [25]:
df[df['age_group'].isnull()][['name', 'age', 'age_group']]

Empty DataFrame
Columns: [name, age, age_group]
Index: []

In [27]:
print(df['age_group'].value_counts())

age_group
Adult          20598
Elderly        20370
Young Adult    13644
Child            888
Name: count, dtype: int64

Columns for day and months

In [28]:
df['admission_month'] = df['date_of_admission'].dt.strftime('%B')

In [29]:
df['day_of_week'] = df['date_of_admission'].dt.strftime('%A')

In [30]:
df.head()

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results,length_of_stay,age_group,admission_month,day_of_week
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.28131,328,Urgent,2024-02-02,Paracetamol,Normal,2,Young Adult,January,Wednesday
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.32729,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6,Elderly,August,Tuesday
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.09608,205,Emergency,2022-10-07,Aspirin,Normal,15,Elderly,September,Thursday
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.78241,450,Elective,2020-12-18,Ibuprofen,Abnormal,30,Young Adult,November,Wednesday
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.31781,458,Urgent,2022-10-09,Penicillin,Abnormal,20,Adult,September,Monday

Exploratory Data Analysis

In [31]:
df['medical_condition'].value_counts()

medical_condition
Arthritis       9308
Diabetes        9304
Hypertension    9245
Obesity         9231
Cancer          9227
Asthma          9185
Name: count, dtype: int64

In [32]:
df['gender'].value_counts()

gender
Male      27774
Female    27726
Name: count, dtype: int64

In [33]:
df['billing_amount'].mean()

np.float64(25539.316097199626)

Visualization